#!/usr/bin/env python3
import sys, json, csv
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path.home() / '.hermes' / 'youtube-transcripts'))
from channel_relevance_filter import get_channel_relevance

BASE = Path.home() / '.hermes' / 'youtube-transcripts'
TODAY = datetime.now().strftime('%Y-%m-%d')
TODAY_DIR = BASE / TODAY

TOPICS = {
    'AI/ML': 'AI & ML', 'Tech': 'Technology', 'Space': 'Space',
    'Geopolitics': 'Geopolitics', 'Health': 'Health', 'Business': 'Business', 'Finance': 'Finance',
}

KWS = {
    'AI/ML': ['ai ', 'llm', 'gpt', 'claude', 'openai', 'machine learning', 'deep learning', 'transformer', 'agi', 'chatgpt', 'anthropic'],
    'Tech': ['tech', 'software', 'coding', 'api', 'cloud', 'nvidia', 'google', 'microsoft', 'programming'],
    'Space': ['space', 'nasa', 'spacex', 'rocket', 'mars', 'moon', 'orbital', 'satellite'],
    'Geopolitics': ['war', 'russia', 'china', 'iran', 'ukraine', 'trump', 'tariff', 'election'],
    'Health': ['health', 'fitness', 'longevity', 'aging', 'neuroscience', 'sauna'],
    'Business': ['business', 'ceo', 'startup', 'strategy', 'revenue', 'funding', 'ipo'],
    'Finance': ['bitcoin', 'crypto', 'stock', 'market', 'etf', 'trading'],
}

def score_content(text):
    t = text.lower()
    scores = {}
    for tp in TOPICS:
        scores[tp] = sum(min(t.count(kw), 4) * (1.5 if 'AI' in tp else 1.0) for kw in KWS.get(tp, []))
    best = max(scores.items(), key=lambda x: x[1])
    return TOPICS.get(best[0], 'General'), best[1]

videos = []
for f in sorted(TODAY_DIR.glob('*.json')):
    if f.name == '_summary.json':
        continue
    try:
        with open(f) as fp:
            d = json.load(fp)
        ch = d.get('channel', 'Unknown')
        title = d.get('title', 'Untitled')
        vid = (d.get('id', '') or f.stem).strip()
        wc = d.get('word_count', 0)
        
        rel = get_channel_relevance(ch)
        topic, ps = score_content(f'{title} {ch}')
        score_val = round(rel.get('score', 2) + ps * 0.5, 1)
        
        reason = 'High signal' if score_val >= 7 else ('Medium signal' if score_val >= 4 else 'Standard')
        reason += f' - {topic}'
        
        if vid:
            videos.append({
                'title': title[:80],
                'channel': ch,
                'duration': f'{wc//200}min',
                'words': wc,
                'topic': topic,
                'score': score_val,
                'reason': reason,
                'url': f'https://youtube.com/watch?v={vid}'
            })
    except:
        continue

videos.sort(key=lambda x: (-x['score'], -x['words']))
total = len(videos)
high = sum(1 for v in videos if v['score'] >= 7)

# Build table rows
rows = ''
for i, v in enumerate(videos[:200], 1):
    rows += f'<tr><td>{i}</td><td>{v["title"]}</td><td>{v["channel"]}</td><td>{v["duration"]}</td><td>{v["topic"]}</td><td>{v["score"]}</td><td>{v["reason"]}</td></tr>'

html = f'''<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>YT Import Report - {TODAY}</title>
<style>
@page{{size:A4;margin:0.5cm}}
*{{box-sizing:border-box;margin:0;padding:0}}
body{{font-family:Arial,sans-serif;background:#fff;color:#1a1a2e;line-height:1.4;font-size:10px}}
.h{{background:linear-gradient(135deg,#3b82f6,#8b5cf6);color:#fff;padding:20px;text-align:center}}
.h h1{{font-size:22px;margin-bottom:5px}}
.h p{{font-size:12px;opacity:0.9}}
.m{{display:flex;gap:10px;padding:15px 20px;background:#f8fafc;border-bottom:1px solid #e2e8f0}}
.m div{{flex:1;background:#fff;border:1px solid #e2e8f0;border-radius:8px;padding:12px;text-align:center}}
.m .v{{font-size:20px;font-weight:700;color:#3b82f6}}
.m .l{{font-size:9px;color:#64748b;text-transform:uppercase}}
.t{{padding:15px 20px}}
table{{width:100%;border-collapse:collapse;font-size:9px}}
th{{background:#f1f5f9;padding:8px 6px;text-align:left;border-bottom:2px solid #cbd5e1;font-weight:600;color:#334155}}
td{{padding:6px;border-bottom:1px solid #e2e8f0}}
tr:nth-child(even){{background:#f8fafc}}
.f{{padding:10px 20px;text-align:center;font-size:8px;color:#94a3b8}}
</style></head>
<body>
<div class="h">
<h1>YouTube Import Report</h1>
<p>{TODAY} | Generated by Hermes Agent</p>
</div>
<div class="m">
<div><div class="v">{total}</div><div class="l">Total Videos</div></div>
<div><div class="v">{high}</div><div class="l">High Signal</div></div>
<div><div class="v">{len(set(v["channel"] for v in videos))}</div><div class="l">Channels</div></div>
<div><div class="v">{sum(v["words"] for v in videos):,}</div><div class="l">Words</div></div>
</div>
<div class="t">
<table>
<thead><tr><th>#</th><th>Title</th><th>Channel</th><th>Duration</th><th>Topic</th><th>Score</th><th>Reason</th></tr></thead>
<tbody>{rows}</tbody>
</table>
</div>
<div class="f">Page 1 of 1 | Total rows: {total}</div>
</body></html>'''

out_path = Path.home() / 'projects' / 'news-dashboard' / 'import_report.html'
with open(out_path, 'w') as f:
    f.write(html)
print('HTML: ' + str(out_path) + ' - ' + str(len(html)) + ' bytes')